### Get all the authors in the database
GET http://localhost:3000/authors

### Get single author from the database
GET http://localhost:3000/authors/674f493d7983c6ffd7fc764f

### Insert a new author to the database
POST http://localhost:3000/authors HTTP/1.1
Content-Type: application/json

{
    "firstName": "Cormac",
    "lastName": "McCarthy",
    "dob": "1933-07-20",
    "dod": "2023-06-13",
    "country": "United States",
    "language": "English",
    "wiki": "https://en.wikipedia.org/wiki/Cormac_McCarthy"
}

### update a author information
PUT http://localhost:3000/authors/674f493d7983c6ffd7fc764f HTTP/1.1
Content-Type: application/json

{
    "firstName": "Joanne",
    "lastName": "Rowling",
    "dob": "1965-07-31",
    "dod": null,
    "country": "England",
    "language": "English",
    "wiki": "https://en.wikipedia.org/wiki/J._K._Rowling"
}

### Delete an author from the database
DELETE http://localhost:3000/authors/674f5d83ad5cbe1eb230f5c0

