### Get all the books in the database
GET http://localhost:3000/books


### Get single book from the database
GET http://localhost:3000/books/674e9051d8a0e1389c0390e7


### Get book items from the database
GET http://localhost:3000/books/674e9051d8a0e1389c0390e7/items


### Get book details from the database
GET http://localhost:3000/books/674e9051d8a0e1389c0390e7/details




### Insert a new book to the database
POST http://localhost:3000/books
Content-Type: application/json


{
  "title": "Harry Potter and the Goblet of Fire",
  "authorId": "674f493d7983c6ffd7fc764f",
  "isbn": "9780439139601",
  "edition": "Paperback",
  "pubDate": "2000-07-08",
  "genre": "Fantasy",
  "cover": "https://m.media-amazon.com/images/I/91-LL7OnDCL._AC_UF1000,1000_QL80_.jpg"
}


### update a book information
PUT http://localhost:3000/books/674e900dd8a0e1389c0390e4
Content-Type: application/json

{
  "authorId": "675001e25bebe4ee950a1b0d"
}


### Delete book item
DELETE http://localhost:3000/books/6750be446deba23db5ba3033